name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

categories:
  - title: "⬆️ Breaking"
    label: "breaking"
  - title: "🚀 New"
    label: "feature"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🛠 Maintenance"
    label: "maintenance"
  - title: "📖 Documentation"
    label: "docs"
  - title: "Other changes"
  - title: "🛡️ Dependency Updates"
    label: "dependencies"
    collapse-after: 5

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bug"
      - "maintenance"
      - "docs"
      - "dependencies"
      - "security"

autolabeler:
  - label: "docs"
    files:
      - "*.md"
    branch:
      - '/docs\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "feature"
    branch:
      - '/feature\/.+/'
    body:
      - "/JIRA-[0-9]{1,4}/"
  - label: "skip-changelog"
    branch:
      # - "develop"
      # - "feat"
      - "/release-.+/"

exclude-labels:
  - "skip-changelog"
