exclude: (alembic/versions|alembic/env|core/bin|sink-connect/connect-plugins)

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=2048
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: ^core/engines/
        args:
          - --unsafe

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
            "--ignore-init-module-imports",
            "--recursive",
          ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --src=webapp
        name: isort (python)
        files: ^webapp/
      - id: isort
        args:
          - --src=webapp
        name: isort (cython)
        types: [cython]
        files: ^webapp/
      - id: isort
        args:
          - --src=webapp
        name: isort (pyi)
        types: [pyi]
        files: ^webapp/

  # - repo: https://github.com/ambv/black
  #   rev: 22.3.0
  #   hooks:
  #     - id: black
  #       args:
  #         - --line-length=100
  #         - --target-version=py310

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         - flake8-bugbear
  #         - flake8-bandit
  #         - flake8-blind-except
  #         - flake8-docstrings
  #         - flake8-logging-format
  #         - flake8-print
  #         - flake8-isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff-format
        types_or: [python, pyi, jupyter]
      - id: ruff
        types_or: [python, pyi, jupyter]
        args:
          - --fix

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        files: ^webapp/
        args:
          - --config-file=mypy.webapp.ini
          - --explicit-package-bases
        additional_dependencies:
          - "types-pytz"
          - "types-PyYAML"
          - "types-requests"
          - "types-confluent-kafka"
          - "types-pika"
          - "types-redis"
          - fastapi[all]>=0.115.5
          - fastapi-pagination[sqlalchemy]>=0.12.34
          - pydantic>=2.10.1
          - pydantic-extra-types>=2.10.0
          - pydantic-settings[yaml]>=2.6.1
          - pytz>=2024.2
          - uvicorn[standard]>=0.32.1
          - loguru>=0.7.2
          - tenacity>=9.0.0
          - requests>=2.32.3
          - jinja2>=3.1.4
          - orjson>=3.10,<4
          - sse-starlette>=2.1.3
          - sqlalchemy>=2.0.36
          - alembic>=1.14.0
          - psycopg2-binary>=2.9.10
          - elasticsearch[async]>=8.17.0

  # - repo: https://github.com/PyCQA/bandit
  #   rev: "1.7.10"
  #   hooks:
  #     - id: bandit
  #       args: ["-c", "bandit.yaml", "-r", "."]
