"""empty message

Revision ID: 282e41766354
Revises: a7fd7bbc6040
Create Date: 2025-01-15 17:27:19.675378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282e41766354'
down_revision = 'a7fd7bbc6040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
